/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoactionapp;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author joegr
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setTitle("Eco Action Planner");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Ensure jPanelBackgroundPanel has CardLayout set in the GUI Designer
        jPanelBackground.setLayout(new CardLayout());

        // Adding panels to jPanelBackgroundPanel with unique identifiers
        jPanelBackground.add(jPanelDash, "jPanelDash");
        jPanelBackground.add(jPanelUser, "jPanelUser");
        jPanelBackground.add(jPanelAction, "jPanelAction");

        // By default, show the dashboard panel when the app starts
        CardLayout cardLayout = (CardLayout) jPanelBackground.getLayout();
        cardLayout.show(jPanelBackground, "jPanelDash");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelAction = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTransportType = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabelModeTransport = new javax.swing.JLabel();
        jLabelDistanceTravelled = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelEnergySaved = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAction = new javax.swing.JTable();
        jButtonSaveTransport = new javax.swing.JButton();
        jButtonClearTransport = new javax.swing.JButton();
        jButtonEnergySave = new javax.swing.JButton();
        jButtonEnergyClear = new javax.swing.JButton();
        jButtonDashImpact = new javax.swing.JButton();
        jButtonUserImpact = new javax.swing.JButton();
        jPanelDash = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelEcoActionPlanner = new javax.swing.JLabel();
        jButtonLoginSignup = new javax.swing.JButton();
        jButtonImpact = new javax.swing.JButton();
        jLabelAuthor = new javax.swing.JLabel();
        jPanelUser = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelBackground.setBackground(new java.awt.Color(0, 153, 153));
        jPanelBackground.setLayout(new java.awt.CardLayout());

        jPanelAction.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Transport Actions");

        jComboBoxTransportType.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxTransportType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxTransportType.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxTransportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Walk", "Bike", "Bus" }));
        jComboBoxTransportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTransportTypeActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabelModeTransport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelModeTransport.setForeground(new java.awt.Color(51, 51, 51));
        jLabelModeTransport.setText("Select Mode of Transport");

        jLabelDistanceTravelled.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDistanceTravelled.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDistanceTravelled.setText("Enter Distance Travelled");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("What did you do?");

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabelEnergySaved.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEnergySaved.setForeground(new java.awt.Color(51, 51, 51));
        jLabelEnergySaved.setText("Energy Saved (kWh)");

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("Energy Saving Actions");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Track your Impact");

        jTableAction.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTableAction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Action Type", "Description", "Impact Measurement", "Date of Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAction);

        jButtonSaveTransport.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSaveTransport.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSaveTransport.setText("Save");

        jButtonClearTransport.setBackground(new java.awt.Color(204, 204, 204));
        jButtonClearTransport.setForeground(new java.awt.Color(51, 51, 51));
        jButtonClearTransport.setText("Clear");

        jButtonEnergySave.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEnergySave.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEnergySave.setText("Save");

        jButtonEnergyClear.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEnergyClear.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEnergyClear.setText("Clear");

        jButtonDashImpact.setBackground(new java.awt.Color(0, 51, 0));
        jButtonDashImpact.setText("Dashboard");
        jButtonDashImpact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashImpactActionPerformed(evt);
            }
        });

        jButtonUserImpact.setBackground(new java.awt.Color(0, 51, 0));
        jButtonUserImpact.setText("User");
        jButtonUserImpact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserImpactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxTransportType, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelModeTransport)
                                .addComponent(jLabel1))
                            .addComponent(jLabelDistanceTravelled)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelActionLayout.createSequentialGroup()
                                .addComponent(jButtonSaveTransport)
                                .addGap(48, 48, 48)
                                .addComponent(jButtonClearTransport)))
                        .addGap(241, 241, 241)
                        .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEnergySaved)
                            .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelActionLayout.createSequentialGroup()
                                .addComponent(jButtonEnergySave)
                                .addGap(38, 38, 38)
                                .addComponent(jButtonEnergyClear))))
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonDashImpact)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUserImpact)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5))
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel6))
                    .addGroup(jPanelActionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(930, Short.MAX_VALUE))
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDashImpact)
                        .addComponent(jButtonUserImpact)))
                .addGap(26, 26, 26)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModeTransport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTransportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistanceTravelled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnergySaved, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveTransport)
                    .addComponent(jButtonClearTransport)
                    .addComponent(jButtonEnergySave)
                    .addComponent(jButtonEnergyClear))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelAction, "card3");

        jPanelDash.setBackground(new java.awt.Color(0, 204, 102));

        jLabelWelcome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(51, 51, 51));
        jLabelWelcome.setText("Welcome to our");

        jLabelEcoActionPlanner.setBackground(new java.awt.Color(0, 102, 51));
        jLabelEcoActionPlanner.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelEcoActionPlanner.setForeground(new java.awt.Color(0, 102, 51));
        jLabelEcoActionPlanner.setText("Eco Action Planner");

        jButtonLoginSignup.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLoginSignup.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLoginSignup.setText("Login / Sign up");
        jButtonLoginSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSignupActionPerformed(evt);
            }
        });

        jButtonImpact.setBackground(new java.awt.Color(204, 204, 204));
        jButtonImpact.setForeground(new java.awt.Color(51, 51, 51));
        jButtonImpact.setText("Track your Impact");
        jButtonImpact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImpactActionPerformed(evt);
            }
        });

        jLabelAuthor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelAuthor.setForeground(new java.awt.Color(51, 51, 51));
        jLabelAuthor.setText("By Joseph Grace and Dylan Earls");

        javax.swing.GroupLayout jPanelDashLayout = new javax.swing.GroupLayout(jPanelDash);
        jPanelDash.setLayout(jPanelDashLayout);
        jPanelDashLayout.setHorizontalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabelWelcome))
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabelEcoActionPlanner))
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabelAuthor))
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButtonLoginSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonImpact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1069, Short.MAX_VALUE))
        );
        jPanelDashLayout.setVerticalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEcoActionPlanner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAuthor)
                .addGap(157, 157, 157)
                .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImpact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoginSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(808, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelDash, "card2");

        jPanelUser.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelUser.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelUser.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1651, Short.MAX_VALUE)
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1277, Short.MAX_VALUE)
        );

        jPanelBackground.add(jPanelUser, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jComboBoxTransportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTransportTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTransportTypeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonLoginSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSignupActionPerformed
    // Get the layout of the mainPanel, cast it to CardLayout
    CardLayout cardLayout = (CardLayout) jPanelBackground.getLayout();
    // Show the user panel by using its name
    cardLayout.show(jPanelBackground, "jPanelUser");
    }//GEN-LAST:event_jButtonLoginSignupActionPerformed

    private void jButtonImpactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImpactActionPerformed
    // Get the layout of the mainPanel, cast it to CardLayout
    CardLayout cardLayout = (CardLayout) jPanelBackground.getLayout();
    // Show the action panel by using its name
    cardLayout.show(jPanelBackground, "jPanelAction");
    }//GEN-LAST:event_jButtonImpactActionPerformed

    private void jButtonDashImpactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashImpactActionPerformed
    // Get the layout of the mainPanel, cast it to CardLayout
    CardLayout cardLayout = (CardLayout) jPanelBackground.getLayout();
    // Show the action panel by using its name
    cardLayout.show(jPanelBackground, "jPanelDash");
    }//GEN-LAST:event_jButtonDashImpactActionPerformed

    private void jButtonUserImpactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserImpactActionPerformed
    // Get the layout of the mainPanel, cast it to CardLayout
    CardLayout cardLayout = (CardLayout) jPanelBackground.getLayout();
    // Show the action panel by using its name
    cardLayout.show(jPanelBackground, "jPanelUser");
    }//GEN-LAST:event_jButtonUserImpactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearTransport;
    private javax.swing.JButton jButtonDashImpact;
    private javax.swing.JButton jButtonEnergyClear;
    private javax.swing.JButton jButtonEnergySave;
    private javax.swing.JButton jButtonImpact;
    private javax.swing.JButton jButtonLoginSignup;
    private javax.swing.JButton jButtonSaveTransport;
    private javax.swing.JButton jButtonUserImpact;
    private javax.swing.JComboBox<String> jComboBoxTransportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelDistanceTravelled;
    private javax.swing.JLabel jLabelEcoActionPlanner;
    private javax.swing.JLabel jLabelEnergySaved;
    private javax.swing.JLabel jLabelModeTransport;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelDash;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAction;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
